services:
  aidcc-genesys-launcher:
    image: ghcr.io/newpaw/infotableaidcc:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - genesysinfotable-data:/app/data
    restart: unless-stopped

volumes:
  genesysinfotable-data:
    name: genesysinfotable-data
